kind: Service
apiVersion: v1
metadata:
  name: gitlab-14
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: gitlab-14
subsets:
  - addresses:
      - ip: 192.168.1.14
    ports:
      - port: 80
        name: http
        protocol: TCP
