kind: Service
apiVersion: v1
metadata:
  name: harbor-146
spec:
  type: ClusterIP
  ports:
    - port: 5443
      name: http
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: harbor-146
subsets:
  - addresses:
      - ip: 192.168.1.146
    ports:
      - port: 5443
        name: http
        protocol: TCP
