---
kind: Service
apiVersion: v1
metadata:
  name: mysql-22
spec:
  type: ClusterIP
  ports:
    - port: 3307
      name: http
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-22
subsets:
  - addresses:
      - ip: 192.168.1.22
    ports:
      - port: 3307
        name: http
        protocol: TCP
