---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-git
  annotations:
    tekton.dev/git-0: http://gitlab-14 # Described below
    tekton.dev/git-1: http://joynova.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: dev
  password: dev123
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-harbor
  annotations:
    tekton.dev/docker-0: harbor.joynova.com:5443 # Described below
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: dev123
