---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: http-trigger
      bindings:
        - ref: pipeline-binding
      template:
        ref: pipeline-template
